### ISSUE TITLE
Webpack 4 Support

### ISSUE THREAD

**Issue by JulioC** [CanopyTax/webpack-system-register#14]
I have a plugin based on webpack-system-register, and we have updated our setup to Webpack 4. They have changed some plugin APIs, so this plugins needs some changes to support that update.

I've identified the following breaking changes:
- Module.meta has been replaced with Module.buildMeta
- buildMeta.harmony has been replaced with buildMeta.exportsType: "namespace"
- chunk.isInitial() was removed, chunk.isOnlyInitial() is an alternative

**Comment by internettrans** [comment]
Released as [`webpack-system-register@1.6.0`](https://github.com/CanopyTax/webpack-system-register/releases/tag/v1.6.0)
